### ISSUE TITLE
Please build and deploy the latest stable production images to GitHub Packages

### ISSUE THREAD

**Issue by joeldesante** [willuhm-js/Dapper#6]
To make deployment less painful, it would be helpful if the latest production-ready builds were deployed to the GitHub package registry. This simplifies the installation process for my cluster.

**Comment by LeoDog896** [comment]
You never specified what *kind* of distribution build you are referring to. I do absolutely agree a Dockerfile in this repository would be useful, but setting a github package would be quite weird. Unless you instead mean to auto-build the distribution files from typescript and bundle them to a zip, and making a pre-release every commit, assuming I'm not missing anything else important in context.

**Comment by joeldesante** [comment]
> You never specified what _kind_ of distribution build you are referring to. I do absolutely agree a Dockerfile in this repository would be useful, but setting a github package would be quite weird. Unless you instead mean to auto-build the distribution files from typescript and bundle them to a zip, and making a pre-release every commit, assuming I'm not missing anything else important in context.

To be more specific. Ideally, when you push to master (assuming that master will always be a stable branch), a GitHub action should build the Docker image, and then post the result to GitHub Packages.

This will allow my container orchestration software to pull the latest stable build directly from GitHub.

**Comment by joeldesante** [comment]
Here is the relevant documentation
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

**Comment by LeoDog896** [comment]
Perfect, thank you for the clarification :+1:

**Comment by LeoDog896** [comment]
I'll reassign this to @willuhm-js.

**Comment by willuhm-js** [comment]
The workflow has been created and a docker image has been released.

**Comment by joeldesante** [comment]
> The workflow has been created and a docker image has been released.

Yay!
