### ISSUE TITLE
Use enviorment variables to set configuration data

### ISSUE THREAD

**Issue by joeldesante** [willuhm-js/dapper#8]
The problem with using a TS file for storing configuration settings is that the application no longer becomes stateless. There is no way for a user, who presumably is pulling the latest build from a registry, to make changes to the config file once the image has been built. Instead, we must set environment variables that can be passed into the container as it boots.

Please use https://www.npmjs.com/package/dotenv to load a .env file or allow for the configuration to default to a environment variable if not manually set.

**Comment by LeoDog896** [comment]
The original author of this repository [already does this](https://github.com/willuhm-js/dapper/blob/master/src/config.ts). Not only does the author have dotenv being loaded into the file, they also go out of their way to reference environment variables and [properly comment](https://github.com/willuhm-js/dapper/blob/fd10b65bb020f94988c814a89ab69940565c1c63/src/config.ts#L11) what each one does.

**Comment by willuhm-js** [comment]
I went ahead and [added env checking](https://github.com/willuhm-js/dapper/commit/ba62608321b2ffc44ab3b598b3d231bb6d333d9b) for the cooldown as that is the only config option without one.

**Comment by joeldesante** [comment]
> The original author of this repository [already has been doing this](https://github.com/willuhm-js/dapper/blob/master/src/config.ts).

Ah sorry, missed that! Thanks!
